### ISSUE TITLE
Call to undefined method `Spatie\Tags\Tag::qgetHighestOrderNumberuery()`

### ISSUE THREAD

**Issue by Anticom** [spatie/eloquent-sortable#85]
I'm using `spatie/nova-tags-field` which in turn uses `spatie/laravel-tags` which again in turn pulls in this package (Version 3.8.0 of this package).

Now if I add some tags to my resource and try to save it I get:
```
[2020-03-20 13:08:09] local.ERROR: Call to undefined method Spatie\Tags\Tag::qgetHighestOrderNumberuery() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Spatie\\Tags\\Tag::qgetHighestOrderNumberuery() at /path/to/project/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
[stacktrace]
#0 /path/to/project/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException()
#1 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1618): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#2 /path/to/project/vendor/spatie/eloquent-sortable/src/SortableTrait.php(173): Illuminate\\Database\\Eloquent\\Model->__call()
#3 /path/to/project/vendor/spatie/eloquent-sortable/src/SortableTrait.php(30): Spatie\\Tags\\Tag->buildSortQuery()
#4 /path/to/project/vendor/spatie/eloquent-sortable/src/SortableTrait.php(25): Spatie\\Tags\\Tag->getHighestOrderNumber()
#5 /path/to/project/vendor/spatie/eloquent-sortable/src/SortableTrait.php(16): Spatie\\Tags\\Tag->setHighestOrderNumber()
#6 /path/to/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Spatie\\Tags\\Tag::Spatie\\EloquentSortable\\{closure}()
#7 /path/to/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#8 /path/to/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(169): Illuminate\\Events\\Dispatcher->dispatch()
#9 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(188): Illuminate\\Events\\Dispatcher->until()
#10 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(787): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#11 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\\Database\\Eloquent\\Model->performInsert()
#12 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(795): Illuminate\\Database\\Eloquent\\Model->save()
#13 /path/to/project/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#14 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(796): tap()
#15 /path/to/project/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#16 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1618): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#17 /path/to/project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\\Database\\Eloquent\\Model->__call()
#18 /path/to/project/vendor/spatie/laravel-tags/src/Tag.php(89): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#19 /path/to/project/vendor/spatie/laravel-tags/src/Tag.php(50): Spatie\\Tags\\Tag::findOrCreateFromString()
#20 [internal function]: Spatie\\Tags\\Tag::Spatie\\Tags\\{closure}()
#21 /path/to/project/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1120): array_map()
#22 /path/to/project/vendor/spatie/laravel-tags/src/Tag.php(51): Illuminate\\Support\\Collection->map()
#23 /path/to/project/vendor/spatie/laravel-tags/src/HasTags.php(220): Spatie\\Tags\\Tag::findOrCreate()
#24 /path/to/project/vendor/spatie/nova-tags-field/src/Tags.php(95): App\\Teaser->syncTagsWithType()
```

I checked the `SortableTrait::buildSortQuery` which is
```php
    public function buildSortQuery()
    {
        return static::qgetHighestOrderNumberuery();
    }
```
but I can't find any implementation of `qgetHighestOrderNumberuery` and also no documentation about this other than you **can** overide `buildSortQuery`.

Please help me out with what I'm missing here.

If you need further information or this is the wrong project for this issue report please let me know.

**Comment by Anticom** [comment]
```sh
$ fgrep -rn qgetHighestOrderNumberuery vendor
vendor/spatie/eloquent-sortable/src/SortableTrait.php:173:        return static::qgetHighestOrderNumberuery();
```

Also [googling](//google.com/search?q=qgetHighestOrderNumberuery) for it didn't yield anything.

**Comment by Anticom** [comment]
Oh lol i must have accidentally edited the file. Consider case closed.
https://giphy.com/gifs/chris-christie-rand-paul-attacks-GfAD7Bl016Gfm/fullscreen
